### ISSUE TITLE
trying to load a none existing SVG file from assets folder throw an exception

### ISSUE THREAD

**Issue by shomronh** [mattsilber/imageloader#2]
Hello first of all Thanks for this great library

this is the error i'm having when using: setTargetUrl()

W/System.err: java.io.FileNotFoundException: https://www.gravatar.com/avatar/59c02e9fd89cfb6fa54b67e846d0631b?d=404
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:218)
W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
W/System.err:     at com.guardanis.imageloader.ImageLoader.download(ImageLoader.java:151)
W/System.err:     at com.guardanis.imageloader.ImageLoader.download(ImageLoader.java:126)
W/System.err:     at com.guardanis.imageloader.ImageDownloader.run(ImageDownloader.java:27)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
D/AndroidRuntime: Shutting down VM
D/eurogoals: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
                 at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:966)
                 at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1014)
                 at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:135)
                 at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:124)
                 at android.graphics.drawable.LayerDrawable$LayerState.newDrawable(LayerDrawable.java:1042)
                 at android.content.res.Resources.getCachedDrawableLocked(Resources.java:2518)
                 at android.content.res.Resources.getCachedDrawable(Resources.java:2486)
                 at android.content.res.Resources.loadDrawable(Resources.java:2350)
                 at android.content.res.Resources.getDrawable(Resources.java:771)
                 at android.content.Context.getDrawable(Context.java:402)
                 at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
                 at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                 at com.guardanis.imageloader.ImageRequest.handleShowStubOnExecute(ImageRequest.java:624)
                 at com.guardanis.imageloader.ImageRequest.access$000(ImageRequest.java:43)
                 at com.guardanis.imageloader.ImageRequest$3.run(ImageRequest.java:659)
                 at android.os.Handler.handleCallback(Handler.java:739)
                 at android.os.Handler.dispatchMessage(Handler.java:95)
                 at android.os.Looper.loop(Looper.java:135)
                 at android.app.ActivityThread.main(ActivityThread.java:5349)
                 at java.lang.reflect.Method.invoke(Native Method)
                 at java.lang.reflect.Method.invoke(Method.java:372)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)

**Comment by shomronh** [comment]
same thing for the setTargetUrl() ....

**Comment by mattsilber** [comment]
You're only getting a warning in the logcat, correct? -- Because a warning is the behavior I intended for this scenario: we want it to log that we tried to access an image that doesn't exist, but we don't want to crash the app because of it.

Or are you trying to say that you're experiencing a full crash from this? And, if so, can you please show me the code block you used for the ImageRequest?

**Comment by shomronh** [comment]
actually yes the app crashes

this is the code i'm using:

```
public static void loadImageFromUrl(final ImageView imageView, final String targetUrl, final int loadingDrawableId, final SVGLoaderResult callback) {

       
                ImageRequest.create(imageView)
                        .setTargetUrl(targetUrl)
                        .setSuccessCallback(new ImageRequest.ImageSuccessCallback() {
                            @Override
                            public void onImageReady(ImageRequest request, Drawable result) {
                                if (callback != null) {
                                    callback.onImageReady(request, result);
                                }
                            }
                        })
                        .setErrorCallback(new ImageRequest.ImageErrorCallback() {
                            @Override
                            public void onImageLoadingFailure(ImageRequest request, @Nullable Throwable e) {
                                if (callback != null) {
                                    callback.onImageLoadingFailure(request, e);
                                }
                            }
                        })
                        .setShowStubOnError(false)
                        .setShowStubOnExecute(true)
                        .overrideStubs(new StubHolder() {
                            @Override
                            public Drawable getLoadingDrawable(Context context) {
                                return ContextCompat.getDrawable(context, loadingDrawableId);
                            }

                            @Override
                            public Drawable getErrorDrawable(Context context) {
                                return null;
                            }
                        })
                        .execute();
          
    }
```

**Comment by mattsilber** [comment]
I ran your code pointing towards "https://www.gravatar.com/avatar/59c02e9fd89cfb6fa54b67e846d0631b?d=404" and the error was both correctly captured and handled by the system.

Following your stacktrace from the bottom, the last call from the library is:

```
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
at com.guardanis.imageloader.ImageRequest.handleShowStubOnExecute(ImageRequest.java:624)
```

The `handleShowStubOnExecute()` inside the `ImageRequest` is trying to load your stub from the `StubHandler` you passed into it, which I believe may be throwing your exception. 

I would check to make sure you can set that specific Drawable directly to a View and see if it throws that same exception (e.g. `imageView.setImageDrawable(ContextCompat.getDrawable(context, loadingDrawableId));` to point you in the right direction.

**Comment by shomronh** [comment]
the file actually exists

**Comment by shomronh** [comment]
so actually the issue was that i did use my method through a static function and this is not a good solution when using a list view : )
for each view holder i'm using a class which has those wrapper functionalities and it's working great

**Comment by mattsilber** [comment]
*Edit:* Glad you figured it out

**Comment by shomronh** [comment]
@mattsilber Thanks a lot for your help

**Comment by shomronh** [comment]
@mattsilber i'm sorry but there is still an issue of the same genr

**Comment by shomronh** [comment]
this is all the stack trace
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:966)
at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1014)
at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:135)
at android.graphics.drawable.LayerDrawable.<init>(LayerDrawable.java:124)
at android.graphics.drawable.LayerDrawable$LayerState.newDrawable(LayerDrawable.java:1042)
at android.content.res.Resources.getCachedDrawableLocked(Resources.java:2518)
at android.content.res.Resources.getCachedDrawable(Resources.java:2486)
at android.content.res.Resources.loadDrawable(Resources.java:2350)
at android.content.res.Resources.getDrawable(Resources.java:771)
at android.content.Context.getDrawable(Context.java:402)
at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:26)
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
at com.guardanis.imageloader.ImageRequest.handleShowStubOnExecute(ImageRequest.java:624)
at com.guardanis.imageloader.ImageRequest.access$000(ImageRequest.java:43)
at com.guardanis.imageloader.ImageRequest$3.run(ImageRequest.java:659)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5349)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
-----------------------------------------------------------

java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:422)
com.google.android.gms.measurement.internal.zzw$zzd.run(Unknown Source)
com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:674)
libcore.io.Streams.readFully(Streams.java:81)
java.io.DataInputStream.readFully(DataInputStream.java:99)
bra.a(:com.google.android.gms.DynamiteModulesC:141)
bra.a(:com.google.android.gms.DynamiteModulesC:34)
bqs.d(:com.google.android.gms.DynamiteModulesC:371)
bqu.run(:com.google.android.gms.DynamiteModulesC:1028)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:422)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
com.google.android.gms.internal.zzqt$zzb.run(Unknown Source)
java.lang.Object.wait(Native Method)
java.lang.Daemons$GCDaemon.run(Daemons.java:341)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
android.net.LocalSocketImpl.accept(Native Method)
android.net.LocalSocketImpl.accept(LocalSocketImpl.java:334)
android.net.LocalServerSocket.accept(LocalServerSocket.java:94)
com.android.tools.fd.runtime.Server$SocketServerThread.run(Server.java:150)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
brb.b(:com.google.android.gms.DynamiteModulesC:126)
brb.a(:com.google.android.gms.DynamiteModulesC:141)
brc.run(:com.google.android.gms.DynamiteModulesC:1022)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
java.lang.Thread.run(Thread.java:818)
android.os.MessageQueue.nativePollOnce(Native Method)
android.os.MessageQueue.next(MessageQueue.java:143)
android.os.Looper.loop(Looper.java:122)
android.os.HandlerThread.run(HandlerThread.java:61)
java.lang.Thread.sleep(Native Method)
java.lang.Thread.sleep(Thread.java:1031)
java.lang.Thread.sleep(Thread.java:985)
java.lang.Daemons$FinalizerWatchdogDaemon.sleepFor(Daemons.java:257)
java.lang.Daemons$FinalizerWatchdogDaemon.waitForFinalization(Daemons.java:268)
java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:216)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1060)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Object.wait(Object.java:422)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:435)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
dalvik.system.VMStack.getThreadStackTrace(Native Method)
java.lang.Thread.getStackTrace(Thread.java:580)
java.lang.Thread.getAllStackTraces(Thread.java:522)
com.tarcha.netminder.MainActivity$4.uncaughtException(MainActivity.java:189)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Thread.sleep(Native Method)
java.lang.Thread.sleep(Thread.java:1031)
java.lang.Thread.sleep(Thread.java:985)
android.os.SystemClock.sleep(SystemClock.java:120)
com.evernote.android.job.JobManager$1.run(JobManager.java:495)
java.lang.String.<init>(String.java:322)
java.lang.String.<init>(String.java:371)
com.google.android.gms.internal.zzaho.zzas(Unknown Source)
com.google.android.gms.internal.zzaho.zzb(Unknown Source)
com.google.android.gms.internal.zzaho.zza(Unknown Source)
com.google.android.gms.internal.zzaka.zzf(Unknown Source)
com.google.android.gms.internal.zzajj$3.zzbxs(Unknown Source)
com.google.android.gms.internal.zzajj$3.call(Unknown Source)
com.google.android.gms.internal.zzaka.zzf(Unknown Source)
com.google.android.gms.internal.zzajj.zzg(Unknown Source)
com.google.android.gms.internal.zzajb.zzf(Unknown Source)
com.google.firebase.database.Query$3.run(Unknown Source)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1048)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:197)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2055)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1060)
java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:776)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
java.lang.Object.wait(Native Method)
java.lang.Thread.parkFor(Thread.java:1220)
sun.misc.Unsafe.park(Unsafe.java:299)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2016)
java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)
```

**Comment by shomronh** [comment]
but:

if i initialize an ImageView with something like: leftImageView.setImageResource(R.drawable.circle);
then use the ImageLoader to insert a new image, it work.

but again how do i make it work ? i'ts like this:

```
public void loadImageFromUrlWithoutVerification(final ImageView imageView, final String targetUrl, final SVGLoaderResult callback) {
        ImageRequest.create(imageView)
                .setTargetUrl(targetUrl)
                .setSuccessCallback(new ImageRequest.ImageSuccessCallback() {
                    @Override
                    public void onImageReady(ImageRequest request, Drawable result) {
                        if (callback != null) {
                            callback.onImageReady(request, result);
                        }
                    }
                })
                .setErrorCallback(new ImageRequest.ImageErrorCallback() {
                    @Override
                    public void onImageLoadingFailure(ImageRequest request, @Nullable Throwable e) {
                        if (callback != null) {
                            callback.onImageLoadingFailure(request, e);
                        }
                    }
                })
                .execute();
    }

    public void loadImageFromUrlWithVerification(final ImageView imageView, final String targetUrl, final SVGLoaderResult callback) {

        if (action != null) {
            action.cancel();
        }

        action = Utils.isFileExists(targetUrl, new Utils.ResultListener() {
            @Override
            public void onComplete() {
                loadImageFromUrlWithoutVerification(imageView, targetUrl, callback);
            }

            @Override
            public void onError() {
                if (callback != null) {
                    callback.onImageLoadingFailure(null, null);
                }
            }
        });
    }
```

**Comment by mattsilber** [comment]
Again, if you look at the stacktrace, the last calls made in the imageloader library before your Exception are:

```
at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
at com.guardanis.imageloader.ImageRequest.handleShowStubOnExecute(ImageRequest.java:624)
```

This shows me that there's something wrong with your loading stub. i.e. whatever Drawable you're trying to load via `ContextCompat.getDrawable(Context, Int)` in the StubHandler you use when creating your ImageRequest is throwing that error; not the library itself.

**Comment by shomronh** [comment]
you are right logically this is the issue but actually that file exist, actually i'm using a library called: RoundedImageView perhaps using your library and this one is not directly copatible
to avoid this exception as i said i'm always reinitialize the RoundedImageView object with a drawable item before using your.

Thanks a lot : )
